//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySaloonProj.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentOrders
    {
        public int ID { get; set; }
        public int ServiceID { get; set; }
        public int ClientID { get; set; }
        public int MasterID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Masters Masters { get; set; }
        public virtual Services Services { get; set; }
    }
}
